server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://120.77.183.198:3306/testMyBatisPlus?useUnicode=true&characterEncoding=utf8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: 1#配置逻辑删除字段为1是删除
      logic-not-delete-value: 0#配置逻辑删除字段为101001是未删除